<a href="https://colab.research.google.com/github/bbcx-investments/notebooks/blob/main/risk/long_run_risk_duplicate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from scipy.stats import norm

# example normal distribution of returns
mean = 0.06
standard_deviation = 0.15
rv = norm(loc=mean, scale=standard_deviation)

# example year invested
T = 20
# simulating T returns from the normal distribution
ret = rv.rvs(T)
ret

array([-0.06972289,  0.11769712, -0.10195943,  0.0207352 , -0.06389311,
        0.14347925,  0.1145414 , -0.1837448 ,  0.10934071,  0.11618244,
        0.25406092,  0.10639495,  0.02648027,  0.04231794, -0.01457973,
        0.13316751,  0.0611446 ,  0.04521094,  0.16515699, -0.28832011])

In [ ]:
compounded_return = (1+ret).prod()
print('The simulated compounded return of', T, 'years is', compounded_return, 'when the returns are normally distributed with mean', mean, 'and standard deviation', standard_deviation)

The simulated compounded return of 20 years is 1.7521224276536829 when the returns are normally distributed with mean 0.06 and standard deviation 0.15


We can simulate more compounded returns to have a simulated distribution of compounded returns.

In [ ]:
numsims = 1000  # number of simulations
ret = rv.rvs(T * numsims).reshape((T, numsims))
ret

array([[-0.12242725,  0.25358241,  0.16062799, ...,  0.08189682,
         0.01060343,  0.34349626],
       [-0.01009158, -0.05188351,  0.08697277, ...,  0.35358607,
         0.14171535, -0.10667026],
       [ 0.17283248, -0.15319189,  0.11701218, ..., -0.05490359,
        -0.00795807, -0.10978874],
       ...,
       [-0.02963732,  0.25699399,  0.067351  , ..., -0.02245067,
         0.02582703,  0.23888679],
       [ 0.03311986, -0.04535221, -0.01975286, ...,  0.08585981,
         0.31723866,  0.01938661],
       [-0.10356626,  0.30194695,  0.11489576, ...,  0.07293602,
        -0.10213051,  0.07949275]])

In [ ]:
compounded_returns = (1 + ret).prod(axis=0)
compounded_returns

array([ 3.20242347,  2.85369312,  6.26097567,  1.48997341,  1.84502687,
        4.21011223,  2.94715002,  3.65562698,  2.62589043,  1.44885409,
        4.7705293 ,  2.83094437,  1.35497905,  7.67302403,  4.14880854,
        1.40609384,  0.65897482,  3.47110346,  2.31908498,  0.70682392,
        2.72226074,  1.20059702,  2.03725733,  3.16550605,  3.21789199,
        1.96345014,  0.67805368,  1.71094998,  0.80889632,  1.04379227,
        3.62890067,  2.81230963,  2.15660443,  3.74528055,  1.77048983,
        1.18781296,  2.33006194,  1.27136995,  6.8875226 ,  1.62214105,
        2.81066759,  8.0156436 ,  1.76890909,  6.30768238,  6.2716959 ,
        5.42126953,  3.13696766,  3.32478015,  3.55719008,  3.04067815,
        7.68748368,  3.51937884,  6.23615697,  1.54688748,  5.26488857,
        6.73664062,  4.2383261 ,  1.73508216,  0.30428546,  2.33314603,
        3.03669671,  0.83485967,  0.85818562,  0.74351972,  2.99342016,
        2.50610851,  0.3503734 ,  2.01606026,  3.1654387 ,  3.45

In [ ]:
import pandas as pd
df = pd.DataFrame(compounded_returns)
df.describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9])

0
count  1000.000000
mean      3.248704
std       2.355324
min       0.152253
10%       1.141695
25%       1.677788
50%       2.634067
75%       4.101796
90%       6.374739
max      26.401474